# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1263, 825)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.link_video = QtWidgets.QLineEdit(self.centralwidget)
        self.link_video.setGeometry(QtCore.QRect(120, 60, 221, 20))
        self.link_video.setObjectName("link_video")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 111, 16))
        self.label.setObjectName("label")
        self.btnLink = QtWidgets.QToolButton(self.centralwidget)
        self.btnLink.setGeometry(QtCore.QRect(340, 60, 25, 19))
        self.btnLink.setObjectName("btnLink")
        self.videoFrame = QtWidgets.QFrame(self.centralwidget)
        self.videoFrame.setGeometry(QtCore.QRect(20, 220, 701, 481))
        self.videoFrame.setAutoFillBackground(True)
        self.videoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.videoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoFrame.setObjectName("videoFrame")
        self.btnPlay = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlay.setGeometry(QtCore.QRect(300, 700, 75, 23))
        self.btnPlay.setObjectName("btnPlay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1263, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "People Counter"))
        self.label.setText(_translate("MainWindow", "Ссылка на видео"))
        self.btnLink.setText(_translate("MainWindow", "..."))
        self.btnPlay.setText(_translate("MainWindow", "A"))
